# Generated by Django 4.0.4 on 2022-04-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bank_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='BIC',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
