# Generated by Django 4.0.4 on 2022-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_bank_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banks',
            field=models.ManyToManyField(to='bankapp.bank'),
        ),
    ]
