# Generated by Django 4.0.4 on 2022-04-23 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_user_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amount', models.PositiveSmallIntegerField(default=0)),
                ('bank', models.ManyToManyField(to='bankapp.bank')),
            ],
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.FloatField(default=1)),
                ('bank', models.ManyToManyField(to='bankapp.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.bank')),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankapp.interestrate')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankapp.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.bank')),
                ('interest_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankapp.interestrate')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankapp.month')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
