# Generated by Django 4.0.4 on 2022-04-24 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_month_interestrate_deposit_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('PAN', models.CharField(default='', max_length=9, unique=True)),
                ('address', models.CharField(default='', max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.company')),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bankapp.month')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Operator', 'Operator'), ('Administrator', 'Administrator')], default='Client', max_length=30),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='installment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
